import React, { useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { Badge, Button, Card, CardHeader, Icon, Tabs, cn } from '../../components/ui/primitives'
import { Drawer, useToast } from '../../components/ui/overlay'
import { EmptyState } from '../../components/ui/states'
import { PageHeader } from '../../components/admin/PageHeader'
import { DemoNote, KpiCard, MetricRow } from '../../components/shared'
import { RECOMMENDATIONS, type Recommendation } from '../../lib/data/analytics'

const PRIORITY_TONE: Record<string, 'clay' | 'gold' | 'neutral'> = { High: 'clay', Medium: 'gold', Low: 'neutral' }

const CATEGORIES = ['All', ...Array.from(new Set(RECOMMENDATIONS.map((r) => r.category)))]

export default function Recommendations() {
  const { push } = useToast()
  const [items, setItems] = useState(RECOMMENDATIONS)
  const [category, setCategory] = useState('All')
  const [priority, setPriority] = useState('all')
  const [saved, setSaved] = useState<string[]>(['rc-2'])
  const [tab, setTab] = useState('all')
  const [active, setActive] = useState<Recommendation | null>(null)

  const rows = useMemo(() => {
    let r = items
    if (category !== 'All') r = r.filter((x) => x.category === category)
    if (priority !== 'all') r = r.filter((x) => x.priority === priority)
    if (tab === 'saved') r = r.filter((x) => saved.includes(x.id))
    return r
  }, [items, category, priority, tab, saved])

  return (
    <div>
      <PageHeader
        eyebrow="MenuMatrix Dining Intelligence"
        title="Business Recommendations"
        subtitle="A prioritised queue of illustrative actions across menu, pricing, promotions, inventory and customers."
        demoNote="Illustrative recommendation — these cards are hand-written examples, not generated by an AI or machine-learning system."
      />

      <div className="mb-5 grid gap-3.5 sm:grid-cols-2 xl:grid-cols-4">
        <KpiCard label="Open recommendations" value={`${items.length}`} compare="in this demo queue" icon="Lightbulb" tone="ember" />
        <KpiCard label="High priority" value={`${items.filter((r) => r.priority === 'High').length}`} compare="act on these first" icon="AlertTriangle" tone="clay" />
        <KpiCard label="Saved for later" value={`${saved.length}`} compare="demo bookmarks" icon="Bookmark" tone="gold" />
        <KpiCard label="Estimated impact" value="Rs. 128K" compare="illustrative monthly" icon="TrendingUp" tone="sage" />
      </div>

      <Card>
        <div className="border-b border-line px-4 pt-3.5">
          <Tabs
            value={tab}
            onChange={setTab}
            tabs={[
              { label: 'All recommendations', value: 'all', count: items.length },
              { label: 'Saved', value: 'saved', count: saved.length },
            ]}
          />
        </div>

        <div className="flex flex-wrap items-center gap-2 border-b border-line px-4 py-3">
          <div className="flex flex-wrap gap-1.5">
            {CATEGORIES.map((c) => (
              <button
                key={c}
                onClick={() => setCategory(c)}
                className={cn(
                  'focus-ring rounded-full border px-3 py-1.5 text-[12px] font-semibold transition-colors',
                  category === c ? 'border-ember-600 bg-ember-600 text-white' : 'border-line-strong bg-white text-ink-soft hover:border-ink-faint',
                )}
              >
                {c}
              </button>
            ))}
          </div>
          <select
            value={priority}
            onChange={(e) => setPriority(e.target.value)}
            className="focus-ring ml-auto h-9 rounded-xl border border-line-strong bg-white px-3 text-[12.5px] font-medium"
            aria-label="Priority"
          >
            <option value="all">Any priority</option>
            <option value="High">High</option>
            <option value="Medium">Medium</option>
            <option value="Low">Low</option>
          </select>
        </div>

        {rows.length === 0 ? (
          <EmptyState
            variant="generic"
            title={tab === 'saved' ? 'Nothing saved yet' : 'No recommendations in this view'}
            message={
              tab === 'saved'
                ? 'Save a recommendation and it will be kept here for your next planning session.'
                : 'Try a different category or priority filter.'
            }
            action={
              <Button
                size="sm"
                variant="secondary"
                icon="RotateCcw"
                onClick={() => {
                  setCategory('All')
                  setPriority('all')
                }}
              >
                Clear filters
              </Button>
            }
          />
        ) : (
          <div className="grid gap-4 p-4 lg:grid-cols-2 xl:grid-cols-3">
            {rows.map((r) => {
              const isSaved = saved.includes(r.id)
              return (
                <Card key={r.id} className="flex flex-col overflow-hidden">
                  <div className="h-1 w-full" style={{ background: r.tone }} />
                  <div className="flex flex-1 flex-col p-4">
                    <div className="flex items-start justify-between gap-2">
                      <span className="text-[10.5px] font-bold uppercase tracking-[0.09em]" style={{ color: r.tone }}>
                        {r.category}
                      </span>
                      <Badge tone={PRIORITY_TONE[r.priority] ?? 'neutral'}>{r.priority}</Badge>
                    </div>

                    <h3 className="mt-2 font-display text-[15.5px] font-semibold leading-snug text-ink">{r.title}</h3>
                    <p className="mt-1.5 flex-1 text-[12.5px] leading-relaxed text-ink-muted">{r.description}</p>

                    <div className="mt-3 grid grid-cols-3 gap-2">
                      {r.metrics.map((m) => (
                        <div key={m.label} className="rounded-lg bg-canvas px-2 py-1.5">
                          <p className="truncate text-[9.5px] font-bold uppercase tracking-wide text-ink-faint">{m.label}</p>
                          <p className="mt-0.5 truncate text-[12.5px] font-semibold text-ink">{m.value}</p>
                        </div>
                      ))}
                    </div>

                    <div className="mt-3 rounded-lg border border-dashed border-line-strong px-2.5 py-2">
                      <p className="text-[10px] font-bold uppercase tracking-wide text-ink-faint">Suggested action</p>
                      <p className="mt-0.5 text-[12px] leading-snug text-ink-soft">{r.action}</p>
                    </div>

                    <div className="mt-3 flex items-center justify-between gap-2 border-t border-line pt-3">
                      <span className="text-[11.5px] font-semibold text-ink-muted">{r.impact}</span>
                      <div className="flex items-center gap-1">
                        <button
                          onClick={() => {
                            setSaved((s) => (s.includes(r.id) ? s.filter((x) => x !== r.id) : [...s, r.id]))
                            push({ title: isSaved ? 'Removed from saved' : 'Saved for later', tone: isSaved ? 'info' : 'success' })
                          }}
                          aria-label={isSaved ? 'Unsave' : 'Save'}
                          className={cn(
                            'focus-ring rounded-lg p-1.5 transition-colors',
                            isSaved ? 'text-gold-600 hover:bg-gold-50' : 'text-ink-faint hover:bg-canvas hover:text-ink',
                          )}
                        >
                          <Icon name="Bookmark" size={15} className={isSaved ? 'fill-gold-500' : ''} />
                        </button>
                        <button
                          onClick={() => {
                            setItems((prev) => prev.filter((x) => x.id !== r.id))
                            push({ title: 'Recommendation dismissed', tone: 'info' })
                          }}
                          aria-label="Dismiss"
                          className="focus-ring rounded-lg p-1.5 text-ink-faint transition-colors hover:bg-clay-50 hover:text-clay-600"
                        >
                          <Icon name="X" size={15} />
                        </button>
                        <Button size="xs" variant="secondary" iconRight="ArrowRight" onClick={() => setActive(r)}>
                          Details
                        </Button>
                      </div>
                    </div>
                  </div>
                </Card>
              )
            })}
          </div>
        )}
      </Card>

      <div className="mt-5 grid gap-4 md:grid-cols-2">
        <Card className="p-5">
          <h3 className="font-display text-[16px] font-semibold text-ink">How these are produced</h3>
          <p className="mt-1.5 text-[13px] leading-relaxed text-ink-muted">
            In this prototype every recommendation is a written example. A production version would connect to restaurant
            data and apply the analytics modules shown elsewhere in DineIQ.
          </p>
          <ul className="mt-3 space-y-2">
            {[
              'Menu performance classification',
              'Market-basket association strength',
              'Price sensitivity grouping',
              'Wastage and inventory thresholds',
            ].map((s) => (
              <li key={s} className="flex items-center gap-2 text-[12.5px] text-ink-soft">
                <Icon name="Check" size={13} className="text-sage-600" />
                {s}
              </li>
            ))}
          </ul>
          <div className="mt-4 flex gap-2">
            <Link to="/admin/menu-intelligence">
              <Button size="sm" variant="secondary" iconRight="ArrowRight">
                Menu intelligence
              </Button>
            </Link>
            <Link to="/admin/market-basket">
              <Button size="sm" variant="ghost" iconRight="ArrowRight">
                Market basket
              </Button>
            </Link>
          </div>
        </Card>

        <Card className="p-5">
          <h3 className="font-display text-[16px] font-semibold text-ink">Dismissing and saving</h3>
          <p className="mt-1.5 text-[13px] leading-relaxed text-ink-muted">
            Dismissed cards disappear from this view and saved cards are kept in the Saved tab. Both actions are local to
            this browser session — nothing is written to a server.
          </p>
          <div className="mt-3 space-y-2">
            <MetricRow label="Illustrative recommendations" value={`${RECOMMENDATIONS.length}`} />
            <MetricRow label="Currently visible" value={`${items.length}`} />
            <MetricRow label="Saved" value={`${saved.length}`} />
          </div>
          <DemoNote className="mt-3">
            Recommendation impact figures are illustrative. No optimisation engine runs in this prototype.
          </DemoNote>
        </Card>
      </div>

      {/* Drawer */}
      <Drawer
        open={!!active}
        onClose={() => setActive(null)}
        title={active?.title ?? ''}
        subtitle={active ? `${active.category} · ${active.priority} priority` : ''}
        width="lg"
        badge={active ? <Badge tone={PRIORITY_TONE[active.priority] ?? 'neutral'}>{active.priority}</Badge> : undefined}
        footer={
          active && (
            <>
              <Button
                variant="secondary"
                icon="Bookmark"
                onClick={() => {
                  setSaved((s) => (s.includes(active.id) ? s : [...s, active.id]))
                  push({ title: 'Saved for later', tone: 'success' })
                }}
              >
                Save
              </Button>
              <Button icon="Check" onClick={() => push({ title: 'Action added to your plan (demo)', tone: 'success' })}>
                Accept action
              </Button>
            </>
          )
        }
      >
        {active && (
          <div className="space-y-4 p-5">
            <Card className="p-4">
              <span className="text-[10.5px] font-bold uppercase tracking-[0.09em]" style={{ color: active.tone }}>
                {active.category}
              </span>
              <p className="mt-2 text-[13.5px] leading-relaxed text-ink-soft">{active.description}</p>
              <div className="mt-3 rounded-xl border border-dashed border-line-strong p-3">
                <p className="text-[10px] font-bold uppercase tracking-wide text-ink-faint">Suggested action</p>
                <p className="mt-1 text-[13px] font-medium text-ink">{active.action}</p>
              </div>
            </Card>

            <div className="grid gap-3 sm:grid-cols-3">
              {active.metrics.map((m) => (
                <div key={m.label} className="rounded-xl border border-line bg-white p-3.5">
                  <p className="text-[10.5px] font-bold uppercase tracking-wide text-ink-faint">{m.label}</p>
                  <p className="mt-0.5 font-display text-[18px] font-semibold text-ink">{m.value}</p>
                </div>
              ))}
            </div>

            <Card className="p-4">
              <p className="text-[13px] font-semibold text-ink">Expected outcome</p>
              <div className="mt-1 divide-y divide-line">
                <MetricRow label="Illustrative impact" value={active.impact.replace('Illustrative impact: ', '')} />
                <MetricRow label="Confidence label" value={active.confidence} />
                <MetricRow label="Priority" value={active.priority} />
                <MetricRow label="Category" value={active.category} />
              </div>
            </Card>

            <Card className="p-4">
              <p className="text-[13px] font-semibold text-ink">Related modules</p>
              <div className="mt-2.5 flex flex-wrap gap-2">
                <Link to="/admin/menu-intelligence">
                  <Button size="xs" variant="secondary" icon="Sparkles">
                    Menu intelligence
                  </Button>
                </Link>
                <Link to="/admin/pricing">
                  <Button size="xs" variant="secondary" icon="Tags">
                    Pricing
                  </Button>
                </Link>
                <Link to="/admin/inventory">
                  <Button size="xs" variant="secondary" icon="PackageMinus">
                    Inventory
                  </Button>
                </Link>
                <Link to="/admin/customers">
                  <Button size="xs" variant="secondary" icon="Users">
                    Customers
                  </Button>
                </Link>
              </div>
            </Card>

            <DemoNote>Illustrative recommendation — not generated by an AI or machine-learning system.</DemoNote>
          </div>
        )}
      </Drawer>
    </div>
  )
}
